### ISSUE TITLE
Pivotal Tracker links

### ISSUE THREAD

**Issue by Quantumplation** [SolidX/HallEnhancementSuite#1]
It should replace text of the form [PT: #id] with a link to the pivotal tracker story.

**Comment by SolidX** [comment]
Early version of this added.
There's a few TODOs such as ensuring it works with multiple PT ids in the same message.

**Comment by Quantumplation** [comment]
Should open in a new tab, instead of the current one.

**Comment by SolidX** [comment]
Added target="_blank" to PT links in v0.42

**Comment by Quantumplation** [comment]
Super Pro Awesome Enhancement Feature: if you already have a PT tab open, use that (takes a long time for PT to load sometimes)
