### ISSUE TITLE
SFW Mode Toggling

### ISSUE THREAD

**Issue by plin25** [SolidX/HallEnhancementSuite#13]
SFW Mode Toggling doesn't work properly

If SFW Mode is turned on, then all images are toggled to Off, but any images posted after this are On. Turning SFW Mode off then reveals all images hidden when SFW Mode was turned on (Off => On), but hides images that were posted after SFW Mode was turned on (On => Off).

Instead of just toggling them, maybe also hide images posted while SFW Mode is on?

**Comment by Quantumplation** [comment]
git checkout -b 78/Saving

er

this isn't my console
