### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by Splagoon** [SolidX/HallEnhancementSuite#2]
In Firefox, the "SFW Mode" button does nothing, and switching rooms causes the conversation to scroll up several messages.

In Internet Explorer 11, Hall hangs for 5-10 seconds when switching rooms.

Perhaps we can improve performance by using web workers?

**Comment by edobry** [comment]
The first two things happen in Chrome as well, probably not browser-specific.

**Comment by Splagoon** [comment]
I'm not getting the first two problems in Chrome Canary.  You're right about regular Chrome, though.

**Comment by SolidX** [comment]
I can't reproduce the FF SFW button issue?

The few seconds of hang in IE 11 are experienced in FF as well. I suspect the cause is that the DOMNodeInserted event for messages is being fired. The fix for that would be to ignore inserted messages when a new room is being opened.

**Comment by Splagoon** [comment]
I tested the SFW button in FF22, 23, and 24, and in all three it does nothing.

**Comment by SolidX** [comment]
Fixed in HES v0.52
