### ISSUE TITLE
:+n:

### ISSUE THREAD

**Issue by SupernaviX** [SolidX/HallEnhancementSuite#8]
Display a bigger thumbs up for a bigger n

**Comment by Quantumplation** [comment]
Perhaps we can generalize this: an emoticon repeated several times just gets bigger each time.

So, :):):):) would be a :) scaled up 4 times.  :+1::+1: would be a :+1: scaled up twice.

**Comment by Quantumplation** [comment]
Alternatively, :+1:*6

**Comment by SupernaviX** [comment]
@RobKellett is this in scope for your slack stylesheet

**Comment by Splagoon** [comment]
no

**Comment by SolidX** [comment]
:sweat_smile: I forgot this was even a thing.
Closing because Hall is dead RIP
