### ISSUE TITLE
Conditional Emoticon Resizing

### ISSUE THREAD

**Issue by EdRyan** [SolidX/HallEnhancementSuite#9]
If you post a message with emoticon(s) but no other text, remove the set height/width so that the emoticon(s) appear full size.

Before
![cer1](https://f.cloud.github.com/assets/647121/1117380/95761624-1a4c-11e3-86ad-c388f90032cc.png)

After
![cer2](https://f.cloud.github.com/assets/647121/1117384/b6d411d6-1a4c-11e3-8896-6936527a1f82.png)

**Comment by Quantumplation** [comment]
Possibly related to #8 ?

**Comment by SolidX** [comment]
@Quantumplation It is related but not quite the same.
I'll implement this and make it so that we can leverage it when implementing issue #8
